ARG DEV_IMAGE
FROM ${DEV_IMAGE}

ARG USER_ID=1000
ARG JAILBOX_INSTALL_CACHE_BUST=""

COPY setup.sh downloader-proxy-manager.sh /tmp/jailbox-container/
RUN : "$JAILBOX_INSTALL_CACHE_BUST" && sh /tmp/jailbox-container/setup.sh && rm -rf /tmp/jailbox-container

COPY entrypoint.sh /usr/local/bin/jailbox-start
RUN chmod +x /usr/local/bin/jailbox-start
COPY jailbox-exec-argv /usr/local/bin/jailbox-exec-argv
RUN chmod 0755 /usr/local/bin/jailbox-exec-argv
COPY write-editor-settings.sh /usr/local/bin/jailbox-write-editor-settings
RUN chmod 0755 /usr/local/bin/jailbox-write-editor-settings
COPY lib/ /usr/local/lib/jailbox/
RUN find /usr/local/lib/jailbox -type d -exec chmod 0755 {} + \
    && find /usr/local/lib/jailbox -type f -exec chmod 0644 {} +

EXPOSE 2222
CMD ["/usr/local/bin/jailbox-start"]
