ARG DEV_IMAGE
FROM ${DEV_IMAGE}

ARG USER_ID=1000
ARG JAILBOX_INSTALL_CACHE_BUST=""

COPY setup.sh /tmp/jailbox-container/
COPY runtime/ /tmp/jailbox-container/runtime/
RUN : "$JAILBOX_INSTALL_CACHE_BUST" && sh /tmp/jailbox-container/setup.sh && rm -rf /tmp/jailbox-container

EXPOSE 2222
CMD ["/usr/local/bin/jailbox-start"]
