ARG DEV_IMAGE
FROM ${DEV_IMAGE}

ARG USER_ID=1000
ARG AI_TOOLS="claude"
ARG EXTRA_PACKAGES=""
ARG CLAUDE_INSTALL_SHA256=""
ARG AIDER_VERSION=""
ARG DEV_USER="devuser"
ARG JAILBOX_INSTALL_CACHE_BUST=""

COPY install/ /tmp/jailbox-install/
RUN : "$JAILBOX_INSTALL_CACHE_BUST" && sh /tmp/jailbox-install/setup.sh && rm -rf /tmp/jailbox-install

COPY jailbox-start /usr/local/bin/jailbox-start
RUN chmod +x /usr/local/bin/jailbox-start

EXPOSE 2222
CMD ["/usr/local/bin/jailbox-start"]
