#!/bin/bash
# Generate the README command reference from the canonical declarations.
set -euo pipefail
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
# shellcheck source=src/public-api.sh
source "$ROOT/src/public-api.sh"
# shellcheck source=src/host/api-support.sh
source "$ROOT/src/host/api-support.sh"
initialize_public_api_lookups
begin='<!-- BEGIN GENERATED: public-api -->'
end='<!-- END GENERATED: public-api -->'
render() {
    local flag command width=0
    local -a commands=()
    for flag in "${CLI_FLAGS_WITH_VALUES[@]}"; do
        commands+=("$flag ${CLI_VALUE_NAMES[$flag]}")
    done
    commands+=("${CLI_FLAGS_WITHOUT_VALUES[@]}")
    for command in "${commands[@]}"; do
        if ((${#command} > width)); then width=${#command}; fi
    done
    printf '%s\n' '<!-- Generated by scripts/gen-public-api.sh; run: bash scripts/gen-public-api.sh --write -->' '```bash'
    for command in "${commands[@]}"; do
        printf 'jailbox %-*s # %s\n' "$width" "$command" "$(cli_flag_help "${command%% *}")"
    done
    printf '%s\n' '```'
}
case "${1:-}" in
    '') render ;;
    --check|--write)
        tmp=$(mktemp -d)
        trap 'rm -rf -- "$tmp"' EXIT
        render > "$tmp/generated"
        awk -v begin="$begin" -v end="$end" '
            $0 == begin {starts++; inside=1; next}
            $0 == end {ends++; inside=0; next}
            inside {print}
            END {if (starts != 1 || ends != 1 || inside) exit 1}
        ' "$ROOT/README.md" > "$tmp/current"
        if [[ "$1" = --check ]]; then
            cmp -s "$tmp/generated" "$tmp/current" || {
                printf 'README command reference is stale; run bash scripts/gen-public-api.sh --write\n' >&2
                exit 1
            }
        else
            awk -v begin="$begin" -v end="$end" -v generated="$tmp/generated" '
                $0 == begin {print; while ((getline line < generated) > 0) print line; close(generated); inside=1; next}
                $0 == end {inside=0}
                !inside {print}
            ' "$ROOT/README.md" > "$tmp/readme"
            cat "$tmp/readme" > "$ROOT/README.md"
        fi
        ;;
    *) printf 'Usage: bash scripts/gen-public-api.sh [--check|--write]\n' >&2; exit 2 ;;
esac
