#!/bin/bash
# Generate the README "Tested Configurations" block from versions.env.
#
# Usage: scripts/gen-tested-matrix.sh [--write|--check]
#   (default)  print the generated block to stdout
#   --write    replace the block between the markers in README.md
#   --check    fail when the README block differs from regeneration, when the
#              tinyproxy Containerfile FROM drifted from BASE_IMAGE_ALPINE, or
#              when dev-images.Containerfile ARG defaults drifted from
#              versions.env
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JAILBOX_DIR="$(dirname "$SCRIPT_DIR")"

# shellcheck source=versions.env
source "$JAILBOX_DIR/versions.env"

README="$JAILBOX_DIR/README.md"
BEGIN_MARKER='<!-- BEGIN GENERATED: tested-matrix -->'
END_MARKER='<!-- END GENERATED: tested-matrix -->'

os_label() {
    local tag="$1"
    local name="${tag%%:*}" version="${tag##*:}"
    printf '%s %s' "$(tr '[:lower:]' '[:upper:]' <<< "${name:0:1}")${name:1}" "$version"
}

gen_block() {
    cat <<EOF
$BEGIN_MARKER
<!-- Generated by scripts/gen-tested-matrix.sh from versions.env. Edit those, then run: bash scripts/gen-tested-matrix.sh --write -->

The release gate installs the exact versions pinned in
[\`versions.env\`](versions.env) — editors, Remote SSH extensions, the
VSCodium REH server, and container base images — so a green gate vouches for
this specific matrix. A daily canary workflow tests every new upstream
release against the full suite and advances the pins automatically when it
passes; failures are tracked as \`canary\`-labeled issues. Alpine/VSCodium is
a best-effort tier: the pinned combination is release-blocking, while
latest-version failures only file issues.

| Container OS | VS Code $CODE_VERSION | VSCodium $CODIUM_VERSION |
|---|---|---|
| $(os_label "$BASE_IMAGE_DEBIAN") | ✅ | ✅ |
| $(os_label "$BASE_IMAGE_ALPINE") | — | ✅ |
| $(os_label "$BASE_IMAGE_FEDORA") | ✅ | ✅ |

VS Code Remote SSH does not support Alpine SSH hosts; that combination is
covered by VSCodium only.

Remote extensions: \`ms-vscode-remote.remote-ssh\` $REMOTE_SSH_VERSION
(VS Code), \`jeanp413.open-remote-ssh\` $OPEN_REMOTE_SSH_VERSION (VSCodium).
VSCodium REH server: $CODIUM_VERSION (commit \`$CODIUM_COMMIT\`).

Last verified: $PINS_LAST_VERIFIED
$END_MARKER
EOF
}

assert_markers() {
    if ! grep -Fxq "$BEGIN_MARKER" "$README" || ! grep -Fxq "$END_MARKER" "$README"; then
        echo "README.md is missing the tested-matrix markers" >&2
        exit 1
    fi
}

write_block() {
    local block_file tmp
    block_file="$(mktemp)"
    tmp="$(mktemp)"
    trap 'rm -f "$block_file" "$tmp"' RETURN

    assert_markers
    gen_block > "$block_file"
    awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v block_file="$block_file" '
        $0 == begin { skip = 1; while ((getline line < block_file) > 0) print line; next }
        $0 == end   { skip = 0; next }
        !skip       { print }
    ' "$README" > "$tmp"
    mv "$tmp" "$README"
}

check_block() {
    local failed=0

    assert_markers
    if ! diff -u \
        <(awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" \
            '$0 == begin { inblock = 1 } inblock { print } $0 == end { inblock = 0 }' "$README") \
        <(gen_block); then
        echo "README tested-matrix block is stale; run: bash scripts/gen-tested-matrix.sh --write" >&2
        failed=1
    fi

    local tinyproxy_from
    tinyproxy_from="$(awk '/^FROM /{print $2; exit}' "$JAILBOX_DIR/container/tinyproxy/Containerfile")"
    if [[ "$tinyproxy_from" != "$BASE_IMAGE_ALPINE" ]]; then
        echo "container/tinyproxy/Containerfile FROM ($tinyproxy_from) != BASE_IMAGE_ALPINE ($BASE_IMAGE_ALPINE)" >&2
        failed=1
    fi

    local key expected actual
    for key in BASE_IMAGE_DEBIAN BASE_IMAGE_ALPINE BASE_IMAGE_FEDORA; do
        expected="${!key}"
        actual="$(sed -n "s/^ARG $key=//p" "$JAILBOX_DIR/tests/integration/dev-images.Containerfile")"
        if [[ "$actual" != "$expected" ]]; then
            echo "dev-images.Containerfile ARG $key ($actual) != versions.env ($expected)" >&2
            failed=1
        fi
    done

    return "$failed"
}

case "${1:-}" in
    "")        gen_block ;;
    --write)   write_block ;;
    --check)   check_block ;;
    *) echo "usage: $(basename "$0") [--write|--check]" >&2; exit 2 ;;
esac
