name: PR Checks

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  test-gates:
    name: required test gates
    uses: ./.github/workflows/test-gates.yml
    with:
      run_editor: false
